(setf apples 35)
(setf oranges 22)
(setf peaches 18)
(setf grapes 10)
(setf bananas 8)
(setf pineapples 5)

(write-line "            Totals")
(write-line "-------------------------------")
(format t "Apples = ~D~C" apples #\linefeed)
(format t "Oranges = ~D~C" oranges #\linefeed)
(format t "Peaches = ~D~C" peaches #\linefeed)
(format t "Grapes = ~D~C" grapes #\linefeed)
(format t "Bananas = ~D~C" bananas #\linefeed)
(format t "Pineapples = ~D~C" pineapples #\linefeed)