import java.util.Scanner

fun main(args: Array<String>) {
    val sc = Scanner(System.`in`)

    print("[1] Enter a NOUN: ")
    val noun1 = sc.nextLine()
    print("[2] Enter a type of VEHICLE: ")
    val vehicle2 = sc.nextLine()
    print("[3] Enter an ADJECTIVE: ")
    val adjective3 = sc.nextLine()
    print("[4] Enter another ADJECTIVE: ")
    val adjective4 = sc.nextLine()
    print("[5] Enter a PLURAL NOUN: ")
    val noun5 = sc.nextLine()
    print("[6] Enter another NOUN: ")
    val noun6 = sc.nextLine()
    print("[7] Enter an ADJECTIVE: ")
    val adjective7 = sc.nextLine()
    print("[8] Enter a VERB that ends in 'ed': ")
    val verb8 = sc.nextLine()
    print("[9] Enter a NOUN: ")
    val noun9 = sc.nextLine()
    print("[10] Enter another NOUN: ")
    val noun10 = sc.nextLine()
    print("[11] Enter yet another NOUN: ")
    val noun11 = sc.nextLine()
    print("[12] Enter a final NOUN: ")
    val noun12 = sc.nextLine()

    println("Just sit right back and you`ll hear a tale,")
    println("A tale of a fateful $noun1,")
    println("That started from this tropic port,")
    println("Aboard this tiny $vehicle2.\n")
    println("The mate was a $adjective3 sailor man,")
    println("The skipper $adjective4 and sure.")
    println("Five $noun5 set sail that day,")
    println("For a three hour $noun6, a three hour $noun6.\n")
    println("The weather started getting $adjective7,")
    println("the tiny $vehicle2 was $verb8.")
    println("If not for the $noun9 of the fearless crew,")
    println("The $noun10 would be lost, the $noun10 would be lost.\n")
    println("The $vehicle2 set ground on the shore of this uncharted desert isle,")
    println("With Gilligan, The Skipper too,")
    println("The millionaire and his $noun11, the movie $noun12,")
    println("And The Rest, Here on Gilligan's Isle.")
}