(write-line "Student Information")
(write-line "------------------------------")
(write-line "John Wayne")
(write-line "4005 Main Street")
(write-line "Denton, Tx 76201")
(write-line "940-382-5000")
(write-line "Junior")
(write-char #\linefeed)
(write-line "Parent or Guardian Information")
(write-line "--------------------------------")
(write-line "Martha Wayne")
(write-line "4005 Main Street")
(write-line "Denton, Tx 76201")
(write-line "940-382-5000")
(write-line "940-387-1515")
(write-line "Denton ISD")